name: Grading workflow
on:
  workflow_dispatch:

jobs:
  grade-learner:
    # if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade gitignore activity
        id: events
        uses: ./.github/actions/check-history-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grading results
        uses: githubtraining/looking-glass-action@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feedback: ${{ steps.events.outputs.reports }}
